/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    news: News;
    contacts: Contact;
    catalogs: Catalog;
    images: Image;
  };
  globals: {};
}
export interface User {
  id: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
  password?: string;
}

export interface News {
  id: string;
  heading?: string;
  body?: {
    [k: string]: unknown;
  }[];
  image?: string | Image;
  createdAt: string;
  updatedAt: string;
}
export interface Image {
  id: string;
  alt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
  createdAt: string;
  updatedAt: string;
}
export interface Contact {
  id: string;
  body?: {
    [k: string]: unknown;
  }[];
  image?: string | Image;
  createdAt: string;
  updatedAt: string;
}
export interface Catalog {
  id: string;
  title?: string;
  items?: {
    image?: string | Image;
    id?: string;
  }[];
  createdAt: string;
  updatedAt: string;
}
